### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by mcannie97** [enjin/Enjin-Minecraft-Plugin#17] opened 2019-09-29 19:50 UTC
on latest 1.14.4 paper + enjin plugin v3.5.12

https://pastebin.com/K32jNugA

**Comment by Favorlock** [comment] 2019-09-29 21:08
I've tested on the build you're using (Paper-195) and could not reproduce this issue. I've also tested on the latest build (Paper-204) and still could not reproduce the issue. I'll need additional information. Please generate an Enjin report and attach the resulting zip file to your next response. I also need to know more about the system environment. Are you using a server host, if so who, if not what are you running the server on (Windows 10, Ubuntu 18.x, etc). What version of Java.

**Comment by mcannie97** [comment] 2019-09-29 22:20
for some reason the problem fixed itself after 2 restarts 🤷
magic

**Comment by Favorlock** [comment] 2019-09-29 22:22
Glad to hear. Must've just been a hick-up in the server. The error you were encountering really should not be occurring as it's a resource being fetched from the plugin jar using the Bukkit API. Will go ahead and close this issue.

**Closed by Favorlock** 2019-09-29 22:22 UTC
Labels: Need More Info, Platform: Paper
